# Generated by Django 5.0.1 on 2024-02-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubapp', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_overview',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_poster_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_release_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
